# Generated by Django 4.1.1 on 2022-09-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUploadDownload', '0002_alter_filedetailsmodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTempStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='storage/temp/')),
            ],
        ),
    ]
